cubox:
  auth: ""  # 扒请求，Authorization Header中的值
  cookie: ""
notion:
  token: "" # https://developers.notion.com/docs
  pageID: ""  # 选定一个页面，会自动在该页面下创建一个数据库。然后将该数据库的ID填入下面的databaseID中
  databaseID: "" # 要归档的数据库的ID
  databaseName: "Cubox归档"
deleteCuboxAfterSave: false # 是否归档成功后删除Cubox对应的文章，建议测试时设置为false，正式使用时设置为true
